# Generated by Django 2.0.3 on 2018-09-17 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180914_1502'),
        ('meupet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='fundacion',
            field=models.ForeignKey(db_column='fundacion', default=0, on_delete=django.db.models.deletion.DO_NOTHING, to='users.MyFundacion'),
            preserve_default=False,
        ),
    ]
