# Generated by Django 2.0.3 on 2018-09-03 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meupet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='chip_id',
            field=models.IntegerField(null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='pet',
            name='sex',
            field=models.CharField(blank=True, choices=[('FE', 'Hembra'), ('MA', 'Macho')], max_length=2),
        ),
        migrations.AlterField(
            model_name='pet',
            name='size',
            field=models.CharField(blank=True, choices=[('SM', 'Pequeño'), ('MD', 'Mediano'), ('LG', 'Grande')], max_length=2),
        ),
    ]
