# Generated by Django 2.0.3 on 2018-09-20 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meupet', '0001_initial'),
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='fundacion',
            field=models.ForeignKey(db_column='fundacion', on_delete=django.db.models.deletion.DO_NOTHING, to='users.Fundacion'),
        ),
        migrations.AddField(
            model_name='pet',
            name='kind',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='meupet.Kind'),
        ),
        migrations.AddField(
            model_name='pet',
            name='owner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='pet',
            name='status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='pets', to='meupet.PetStatus'),
        ),
        migrations.AlterUniqueTogether(
            name='pet',
            unique_together={('name', 'owner')},
        ),
    ]
