# Generated by Django 2.0.3 on 2018-09-03 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meupet', '0002_auto_20180903_1450'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='chip_id',
            field=models.IntegerField(blank=True, null=True, unique=True),
        ),
    ]
