# Generated by Django 2.0.3 on 2018-10-05 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meupet', '0002_auto_20181004_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='edad',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
