# Generated by Django 2.0.3 on 2018-10-05 00:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meupet', '0003_pet_edad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='edad',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
