# Generated by Django 2.0.3 on 2018-09-20 15:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contratos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('adjunto', models.CharField(max_length=250)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
