# Generated by Django 2.0.3 on 2018-09-06 19:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyContratos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('adjunto', models.CharField(max_length=250)),
                ('estado', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'db_table': 'my_contratos',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyRelacion',
            fields=[
                ('usuario', models.ForeignKey(db_column='usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fecha', models.DateTimeField()),
            ],
            options={
                'db_table': 'my_relacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MySeguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('observaciones', models.CharField(blank=True, max_length=250, null=True)),
                ('adjuntos', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'my_seguimiento',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyTipoRelacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'my_tipo_relacion',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='MyVisitas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateTimeField()),
                ('fecha_prox_visita', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.CharField(max_length=250)),
                ('adjuntos', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'my_visitas',
                'managed': False,
            },
        ),
    ]
