# Generated by Django 2.0.3 on 2018-10-01 21:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adopcion', '0001_initial'),
        ('meupet', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacion',
            name='mascota',
            field=models.ForeignKey(db_column='mascota', on_delete=django.db.models.deletion.DO_NOTHING, to='meupet.Pet'),
        ),
        migrations.AddField(
            model_name='relacion',
            name='tipo_relacion',
            field=models.ForeignKey(db_column='tipo_relacion', on_delete=django.db.models.deletion.DO_NOTHING, to='adopcion.TipoRelacion'),
        ),
    ]
