# Generated by Django 2.0.3 on 2018-09-10 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MyFundacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_identificacion', models.CharField(blank=True, choices=[('RUT', 'RUT'), ('NIT', 'NIT')], max_length=3)),
                ('numero_identificacion', models.CharField(max_length=15, unique=True)),
                ('razon_social', models.CharField(blank=True, max_length=250, null=True)),
                ('fecha_fundacion', models.DateTimeField(blank=True, null=True)),
                ('email', models.CharField(blank=True, max_length=250, null=True, unique=True)),
                ('telefono', models.CharField(blank=True, max_length=250, null=True)),
                ('logo', models.CharField(blank=True, max_length=250, null=True)),
                ('contrato_base', models.CharField(blank=True, max_length=250, null=True)),
            ],
            options={
                'db_table': 'my_fundacion',
                'managed': False,
            },
        ),
    ]
