# Generated by Django 2.0.3 on 2018-09-20 15:36

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('meupet', '0001_initial'),
        ('users', '0001_initial'),
        ('adopcion', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relacion',
            fields=[
                ('usuario', models.ForeignKey(db_column='usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fecha', models.DateTimeField()),
                ('contratos', models.ForeignKey(blank=True, db_column='contratos', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adopcion.Contratos')),
                ('mascota', models.ForeignKey(db_column='mascota', on_delete=django.db.models.deletion.DO_NOTHING, to='meupet.Pet')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateTimeField()),
                ('observaciones', models.CharField(blank=True, max_length=250, null=True)),
                ('adjuntos', models.CharField(blank=True, max_length=250, null=True)),
                ('contratos', models.ForeignKey(db_column='contratos', on_delete=django.db.models.deletion.DO_NOTHING, to='adopcion.Contratos')),
            ],
        ),
        migrations.CreateModel(
            name='TipoRelacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.CharField(max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='Visitas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_visita', models.DateTimeField()),
                ('fecha_prox_visita', models.DateTimeField(blank=True, null=True)),
                ('observaciones', models.CharField(max_length=250)),
                ('adjuntos', models.CharField(blank=True, max_length=250, null=True)),
                ('contratos', models.ForeignKey(db_column='contratos', on_delete=django.db.models.deletion.DO_NOTHING, to='adopcion.Contratos')),
            ],
        ),
        migrations.AddField(
            model_name='relacion',
            name='tipo_relacion',
            field=models.ForeignKey(db_column='tipo_relacion', on_delete=django.db.models.deletion.DO_NOTHING, to='adopcion.TipoRelacion'),
        ),
        migrations.AlterUniqueTogether(
            name='relacion',
            unique_together={('usuario', 'mascota')},
        ),
    ]
