# Generated by Django 2.0.3 on 2018-10-01 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('adopcion', '0001_initial'),
        ('meupet', '0001_initial'),
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Relacion',
            fields=[
                ('usuario', models.ForeignKey(db_column='usuario', on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
                ('fecha', models.DateTimeField()),
                ('mascota', models.ForeignKey(db_column='mascota', on_delete=django.db.models.deletion.DO_NOTHING, to='meupet.Pet')),
            ],
        ),
        migrations.CreateModel(
            name='Seguimiento',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('1', 'Evidencia'), ('2', 'Visita'), ('3', 'Contrato')], max_length=1)),
                ('estado', models.CharField(choices=[('1', 'Aprobación'), ('2', 'Anulación'), ('3', 'Pendiente'), ('4', 'Anomalias')], max_length=1)),
                ('fecha', models.DateTimeField()),
                ('descripcion', models.TextField(max_length=2000)),
                ('observaciones', models.TextField(blank=True, max_length=2000, null=True)),
                ('anterior', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adopcion.Seguimiento')),
                ('relacion', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adopcion.Relacion')),
            ],
        ),
        migrations.CreateModel(
            name='TipoRelacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50)),
                ('descripcion', models.TextField(max_length=500)),
                ('observaciones', models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='relacion',
            name='tipo_relacion',
            field=models.ForeignKey(db_column='tipo_relacion', on_delete=django.db.models.deletion.DO_NOTHING, to='adopcion.TipoRelacion'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='contrato_base',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adopcion.Contratos'),
        ),
        migrations.AddField(
            model_name='clausulas',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adopcion.Contratos'),
        ),
        migrations.AddField(
            model_name='adjuntos_seguimiento',
            name='seguimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adopcion.Seguimiento'),
        ),
        migrations.AlterUniqueTogether(
            name='relacion',
            unique_together={('usuario', 'mascota')},
        ),
    ]
