# Generated by Django 2.0.3 on 2018-10-01 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_auto_20181001_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='adjuntos_seguimiento',
            name='letter',
            field=models.CharField(choices=[('A', 'A'), ('B', 'B')], default=1, max_length=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='adjuntos_seguimiento',
            name='number',
            field=models.PositiveIntegerField(choices=[('A', ((1, '1'), (2, '2'), (3, '3'))), ('B', ((4, '4'), (5, '5'), (6, '6')))], default=1, max_length=1),
            preserve_default=False,
        ),
    ]
