# Generated by Django 2.0.3 on 2018-10-04 23:10

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('adopcion', '0002_auto_20181004_1810'),
    ]

    operations = [
        migrations.AddField(
            model_name='relacion',
            name='usuario',
            field=models.ForeignKey(db_column='usuario', on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='contratos',
            name='contrato_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adopcion.Contratos'),
        ),
        migrations.AddField(
            model_name='contratos',
            name='fundacion',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='users.Fundacion'),
        ),
        migrations.AddField(
            model_name='clausulas',
            name='contrato',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adopcion.Contratos'),
        ),
        migrations.AddField(
            model_name='adjuntos_seguimiento',
            name='seguimiento',
            field=models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, to='adopcion.Seguimiento'),
        ),
        migrations.AlterUniqueTogether(
            name='relacion',
            unique_together={('usuario', 'mascota')},
        ),
    ]
