# Generated by Django 2.0.3 on 2018-09-21 22:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0002_auto_20180920_1036'),
    ]

    operations = [
        migrations.CreateModel(
            name='Adjuntos_Contratos_Fundacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adjunto', models.ImageField(help_text='Maximo tamaño de imagen 8mb', upload_to='fundacion_contratos')),
            ],
        ),
        migrations.CreateModel(
            name='Clausulas_Base',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('fecha_agregado', models.DateTimeField()),
                ('descripcion', models.CharField(max_length=250)),
                ('observaciones', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Clausulas_Fundacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('fecha_agregado', models.DateTimeField()),
                ('descripcion', models.CharField(max_length=250)),
                ('observaciones', models.CharField(blank=True, max_length=1000, null=True)),
                ('estado', models.CharField(choices=[('1', 'Aprobada'), ('2', 'Pendiente'), ('3', 'Anulada')], max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='ContratoBase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=250)),
                ('fecha_agregado', models.DateTimeField()),
                ('descripcion', models.CharField(max_length=1000)),
                ('observaciones', models.CharField(max_length=1000)),
            ],
        ),
        migrations.CreateModel(
            name='Contratos_Fundacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('objeto', models.CharField(max_length=250)),
                ('fecha', models.DateTimeField()),
                ('observaciones', models.CharField(max_length=1000)),
                ('estado', models.CharField(choices=[('1', 'Concertado'), ('2', 'Pendiente'), ('3', 'Anulado')], max_length=1)),
            ],
        ),
        migrations.AlterField(
            model_name='relacion',
            name='contratos',
            field=models.ForeignKey(blank=True, db_column='Contratos_Fundacion', null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='adopcion.Contratos_Fundacion'),
        ),
        migrations.AlterField(
            model_name='seguimiento',
            name='contratos',
            field=models.ForeignKey(db_column='Contratos_Fundacion', on_delete=django.db.models.deletion.DO_NOTHING, to='adopcion.Contratos_Fundacion'),
        ),
        migrations.AlterField(
            model_name='visitas',
            name='contratos',
            field=models.ForeignKey(db_column='Contratos_Fundacion', on_delete=django.db.models.deletion.DO_NOTHING, to='adopcion.Contratos_Fundacion'),
        ),
        migrations.DeleteModel(
            name='Contratos',
        ),
        migrations.AddField(
            model_name='clausulas_base',
            name='contrato',
            field=models.ForeignKey(db_column='contrato_base', on_delete=django.db.models.deletion.DO_NOTHING, to='adopcion.ContratoBase'),
        ),
        migrations.AddField(
            model_name='adjuntos_contratos_fundacion',
            name='contrato',
            field=models.ForeignKey(db_column='contrato', on_delete=django.db.models.deletion.DO_NOTHING, to='adopcion.Contratos_Fundacion'),
        ),
    ]
