# Generated by Django 2.0.3 on 2018-10-05 00:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0003_auto_20181004_1810'),
    ]

    operations = [
        migrations.AlterField(
            model_name='seguimiento',
            name='fecha',
            field=models.DateTimeField(default=datetime.datetime(2018, 10, 5, 0, 23, 20, 956440, tzinfo=utc)),
        ),
    ]
