# Generated by Django 2.0.3 on 2018-09-24 15:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0003_auto_20180921_1732'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratobase',
            name='descripcion',
            field=models.TextField(max_length=2000),
        ),
    ]
