# Generated by Django 2.0.3 on 2018-10-01 14:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0003_auto_20181001_0934'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='adjuntos_seguimiento',
            name='letter',
        ),
        migrations.RemoveField(
            model_name='adjuntos_seguimiento',
            name='number',
        ),
    ]
