# Generated by Django 2.0.3 on 2018-10-01 14:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0004_auto_20181001_0941'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='objeto',
            field=models.CharField(choices=[('1', 'Adopción'), ('2', 'Hogar de paso'), ('2', 'Apadrinamiento')], max_length=1),
        ),
    ]
