# Generated by Django 2.0.3 on 2018-10-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0005_auto_20181001_0947'),
    ]

    operations = [
        migrations.AddField(
            model_name='contratos',
            name='nombre',
            field=models.CharField(default=1, max_length=250),
            preserve_default=False,
        ),
    ]
