# Generated by Django 2.0.3 on 2018-10-01 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('adopcion', '0006_contratos_nombre'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contratos',
            name='contrato_base',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='adopcion.Contratos'),
        ),
    ]
