# Generated by Django 2.0.3 on 2018-10-04 23:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Configuration',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fb_share_token', models.TextField(max_length=250)),
                ('fb_share_app_id', models.TextField(max_length=20)),
                ('fb_share_app_secret', models.TextField(max_length=35)),
                ('fb_share_link', models.TextField(max_length=50)),
            ],
        ),
    ]
