# Generated by Django 2.0.3 on 2018-09-06 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='num_identificacion',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='ownerprofile',
            name='tipo_identificacion',
            field=models.CharField(blank=True, choices=[('CC', 'Cedula ciudadania'), ('TI', 'Tarjeta identidad')], max_length=2),
        ),
    ]
