# Generated by Django 2.0.3 on 2018-10-05 00:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundacion',
            name='fecha_fundacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 5, 0, 23, 20, 892423, tzinfo=utc), null=True),
        ),
    ]
