# Generated by Django 2.0.3 on 2018-10-05 00:27

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20181004_1923'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fundacion',
            name='fecha_fundacion',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2018, 10, 5, 0, 27, 58, 276532, tzinfo=utc), null=True),
        ),
    ]
