# Generated by Django 2.0.3 on 2018-09-06 20:24

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_auto_20180906_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='num_identificacion',
            field=models.IntegerField(unique=True, validators=[django.core.validators.MinValueValidator(11111111)], verbose_name='Numero de identificación'),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Telefono de contacto'),
        ),
    ]
