# Generated by Django 2.0.3 on 2018-09-10 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_auto_20180906_1524'),
    ]

    operations = [
        migrations.AddField(
            model_name='ownerprofile',
            name='rol',
            field=models.CharField(blank=True, choices=[('RESP', 'Responsable'), ('VINC', 'Vinculado'), ('BRIG', 'Brigadista')], max_length=4),
        ),
        migrations.AlterField(
            model_name='ownerprofile',
            name='num_identificacion',
            field=models.CharField(max_length=10, unique=True, verbose_name='Numero de identificación'),
        ),
    ]
