# Generated by Django 2.0.3 on 2018-09-10 21:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20180910_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ownerprofile',
            name='rol',
            field=models.CharField(blank=True, choices=[('R_01', 'Responsable'), ('R_02', 'Vinculado'), ('R_03', 'Brigadista')], max_length=4),
        ),
    ]
